#ifndef GLOBAL_H
#define GLOBAL_H

#define PLAYER_SPEED 6
#define ENEMY_SPEED (PLAYER_SPEED / 2)
#define SHELL_SPEED (PLAYER_SPEED * 2)

#define FRAME_DURATION 30

#define DEFAULT_UNIT_DIRECTION 0

#endif // GLOBAL_H
