#pragma once

#define FRAME_DURATION 30

#define PLAYER_SPEED 6
#define ENEMY_SPEED (PLAYER_SPEED / 2)
#define SHELL_SPEED (PLAYER_SPEED * 2)

#define DEFAULT_UNIT_DIRECTION 0

#define ENEMIES_ON_LEVEL 16
#define MAX_RUNNING_ENEMIES 4
#define ENEMY_RESPAWN_INTERVAL 3000
#define AI_TICK_INTERVAL 1000
