#ifndef GLOBAL_H
#define GLOBAL_H

#define MOVE_SPEED 8
#define FRAME_DURATION 30

#define DEFAULT_UNIT_DIRECTION 0

#define BATTLE_SCENE_WIDTH 1024
#define BATTLE_SCENE_HEIGHT 768

#endif // GLOBAL_H
